# Generated by Django 2.0 on 2020-02-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c4d_content',
            fields=[
                ('content_ID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=45)),
                ('data', models.CharField(max_length=45)),
                ('from_url', models.CharField(max_length=150)),
                ('Unit', models.IntegerField(max_length=11)),
                ('trans_content', models.TextField()),
                ('upvode', models.IntegerField(max_length=11)),
                ('author_alias', models.CharField(max_length=45)),
                ('portrait', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'c4d_content',
            },
        ),
        migrations.CreateModel(
            name='C4D_url',
            fields=[
                ('post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.TextField()),
                ('title', models.CharField(max_length=1000)),
                ('replies', models.IntegerField(max_length=11)),
                ('if_scrapied', models.CharField(max_length=30)),
                ('trans_title', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'C4D_url',
            },
        ),
        migrations.AddField(
            model_name='c4d_content',
            name='post_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.C4D_url'),
        ),
    ]
