# Generated by Django 2.0 on 2020-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c4d_url',
            name='if_scrapied',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
