# Generated by Django 2.0 on 2020-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20200214_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c4d_content',
            name='data',
        ),
        migrations.AddField(
            model_name='c4d_content',
            name='time',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
