# Generated by Django 2.0 on 2020-02-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20200214_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c4d_content',
            old_name='time',
            new_name='date',
        ),
    ]
