# Generated by Django 2.0 on 2020-02-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20200214_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c4d_content',
            name='Unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c4d_content',
            name='post_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c4d_content',
            name='upvode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='c4d_url',
            name='replies',
            field=models.IntegerField(),
        ),
    ]
